version: '3'
services:
  javaCRUD:
    image: postgres
    container_name: web
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
    - ./DB/postgres:/var/lib/postgresql/data
    cpus: 0.5
    mem_limit: 512m

